pipeline {
  agent {
    docker {
      image 'bitnami/kubectl:latest'
      args '-v /root/.kube:/root/.kube' // Mount kubeconfig if needed
    }
  }
  stages {
    stage('Apply Manifests') {
      steps {
        sh 'kubectl apply -f k8-manifests/'
      }
    }
    stage('Get Pod Details') {
      steps {
        sh 'kubectl get pods -o wide'
      }
    }
  }
}
