pipeline {
  agent {
    docker {
      image 'bitnami/kubectl:latest'
      args '--entrypoint="" -v /root/.kube:/root/.kube' // Mount kubeconfig if needed
    }
  }
  stages {
    /*stage('Checkout') {
      steps {
        checkout scm
      }
    }*/
    stage('Update Kube Config'){
      steps {
        sh 'aws eks update-kubeconfig --region us-east-1 --name ekspractice'
      }
    }
    stage('Apply Manifests') {
      steps {
	    sh 'ls -la'
        sh 'kubectl apply -f Jenkins/kubectlbinary/k8-manifests/'
      }
    }
    stage('Get Pod Details') {
      steps {
        sh 'kubectl get pods -o wide'
      }
    }
  }
}
